### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [yiwangtz/MENet#1]
Thank you for your great work!
but where is the code 
`import my_config.my_config as my_config`
Looking forward to your reply

**Comment by cenchaojun** [comment]
> Thank you for your great work! but where is the code `import my_config.my_config as my_config` Looking forward to your reply

I had it taken care o

**Comment by WangZheng-ze** [comment]
Hi, bro! I have the same question ? How did you resolve it ? Could you please tell me , thank you !

**Comment by WangZheng-ze** [comment]
@cenchaojun
